#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=baseline_s3
#SBATCH --time=12:00:00
#SBATCH --output=./slurm_out/baseline/s3_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate rq-vae
cd CIKM2020-S3Rec-master

# srun python run_finetune_full.py --data_name Beauty 
# srun python data/data_process.py
srun python build_fairness_data.py --data_name Beauty