#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=install_env
#SBATCH --time=06:00:00
#SBATCH --output=./slurm_out/install_env.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

# Create a clean environment
conda create -n rq-vae python=3.9

source activate rq-vae

# Install project-specific requirements
pip install -r requirements.txt