#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=mmg_rec
#SBATCH --time=12:00:00
#SBATCH --output=./slurm_out/mmg_rec_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate mmg_rec

srun python data_load.py
srun python data_pro.py
srun python src_input.py
srun python tgt_input.py
srun python model_train.py
srun python model_test.py